### ISSUE TITLE
Default button's font-family to Fira

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mofo-bootstrap#102]
related: https://github.com/mozilla/nsf-challenge/pull/16

thoughts? @alanmoo @gvn

**Comment by alanmoo** [comment]
It looks like this comes down to the fact that Normalize inside Bootstrap sets `button { font-family:sans-serif;}`, but `.btn` doesn't set a font, so `a.btn` has Fira but `button.btn` doesn't.

I kind of get why bootstrap does this, but it's not great. I wouldn't be opposed to adding `.btn{font-family: inherit}` or even `font-family: "Fira Sans"` since it is our customization of Bootstrap, after all. Thoughts @gvn? I'm going to dig/open an issue in the main Bootstrap repo about this too.

**Comment by gvn** [comment]
I actually just noticed this today. Let's probably use `inherit` since we may be switching off Fira soon with the new branding.

**Comment by fitojb** [comment]
> we may be switching off Fira soon with the new branding.

For the record, Fira is [staying](https://mozilla.ninja/typography) in the new branding. It wouldn’t be good taste to use a seriffed typeface intended for display sizes in body text.

**Comment by gvn** [comment]
Either way, `inherit` will work for what we're trying to accomplish here.
