### ISSUE TITLE
Add link to Participation Guidelines in footer

### ISSUE THREAD

**Issue by jayyyin** [mozilla/mofo-bootstrap#122]
https://github.com/mozilla/foundation.mozilla.org/issues/235
I'm under the impression that these changes have to take place here, so I'm going to reference this so I get some feedback from people here too.

**Comment by jayyyin** [comment]
@gvn  @kristinashu so I opened this issue, and I've found the footer file and I was wondering how the "url" string is generated, is there something you guys use to put a url through to make that format? and also how would I get the svg into the list?

**Comment by gideonthomas** [comment]
@jayyyin, please look at my comment [here](https://github.com/mozilla/foundation.mozilla.org/issues/235#issuecomment-351616560) before continuing with this issue.

For this specific issue: the lines that need to be changed are here: https://github.com/mozilla/mofo-bootstrap/blob/master/src/index.pug#L238-L239. 
We use a templating library called [pug](https://pugjs.org/api/getting-started.html) which is why the syntax you see there isn't simple html but is like html. Replace the href and the text with `https://www.mozilla.org/about/governance/policies/participation/` and `Participation Guidelines` respectively. This is the simplest approach.

As a bonus, also update the `class` on that line to be `footer-link-participation-guidelines` and update this line: https://github.com/mozilla/mofo-bootstrap/blob/master/src/scss/custom/components/_footer.scss#L65 accordingly. If you do choose to do this, please make sure to mention in your PR that this is a breaking change and we need to do a version bump in `package.json` as well (one of our developers can do that or assist you in doing that).

**Comment by jayyyin** [comment]
@gideonthomas alright I've made the changes what needs to be done in package.json?
